# Generated by Django 6.0.5 on 2026-05-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Catalogue PELAGIC PRO', max_length=150)),
                ('file', models.FileField(upload_to='catalogues/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
